-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Auth.Query exposing (..)

import Auth.InputObject
import Auth.Interface
import Auth.Object
import Auth.Scalar
import Auth.ScalarCodecs
import Auth.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


token : SelectionSet String RootQuery
token =
    Object.selectionForField "String" "token" [] Decode.string
