-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Auth.ScalarCodecs exposing (..)

import Auth.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Upload =
    Auth.Scalar.Upload


codecs : Auth.Scalar.Codecs Upload
codecs =
    Auth.Scalar.defineCodecs
        { codecUpload = defaultCodecs.codecUpload
        }
